nelmio_api_doc:
    documentation:
        info:
            title: Movilnet Food Delivery API
            description: Automated Operational Control for Food Delivery
            version: 1.0.0
        tags:
            - name: Me
            - name: Users
            - name: Employees
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - BearerAuth: []

    areas:
        path_patterns:
            - ^/api(?!/doc$)